config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :usuarios

  scope 'horarios' do
    get '/novo/:hora/:dia' => 'horarios#novo', as: 'horarios_novo'
    get '/excluir/:hora/:dia' => 'horarios#excluir', as: 'horarios_excluir'
  end
end

app/models/horario.rb
class Horario < ActiveRecord::Base
	belongs_to :usuario

	validates_uniqueness_of :horario, scope: :dia
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
  has_many :horarios

  def nome_completo
  	"#{self.nome} #{self.sobrenome}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nome
    devise_parameter_sanitizer.for(:sign_up) << :sobrenome
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_usuario!

  def index
  end
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  before_action :authenticate_usuario!

  def novo
  	@horario=Horario.new
  	hora_formatada=hora_formatada(params[:hora])
  	@horario.horario=hora_formatada
  	@horario.dia=params[:dia]
  	@horario.usuario=current_usuario
  	if @horario.save
  		respond_to do |format|
  	      format.js
  	    end
  	end
  end

  def excluir
  	@horario=Horario.where(horario: hora_formatada(params[:hora]), dia: params[:dia]).first
    @horario.destroy
    respond_to do |format|
       format.js
    end
  end

  def params_whitelist
  	params.permit(:hora,:dia)
  end

  private
  def hora_formatada(hora)
    "#{format('%02d', hora.to_i)}:00"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
	def horario_livre(hora, dia)
		link_to "Agendar", horarios_novo_path(hora,dia), remote: true, data: { confirm: "Confirmar agendamento?" }
	end

	def horario_reservado(horario)
		if current_usuario.id == horario.usuario_id
			"Reservado para #{horario.usuario.nome} #{link_para_exclusao(horario)}".html_safe
		else
			"Reservado para #{horario.usuario.nome}"
		end
	end

	def link_para_exclusao(horario)
		link_to "X", horarios_excluir_path(horario.horario[0..1],horario.dia), remote: true, data: { confirm: "Tem certeza que deseja excluir seu agendamento?" }
	end

	def horario_do_dia(hora, dia)
		hora_foramtada="#{format('%02d', hora)}:00"
		horario=Horario.where(horario: hora_foramtada, dia: dia).first
		if horario
			horario_reservado(horario)
		else
			horario_livre(hora, dia)
		end
	end
end

app/views/home/index.html.erb
<table role="grid">
<thead>
	<tr>
		<th>Horário</th>
		<th>Segunda</th>
		<th>Terça</th>
		<th>Quarta</th>
		<th>Quinta</th>
		<th>Sexta</th>
	</tr>
</thead>
<tbody>
	<% (6..23).each do |hora| %>
	<tr>
		<td><%= "#{format('%02d', hora)}:00" %>
		
		<% (2..6).each do |dia| %>
			<td>
			<div id="dia_<%= format('%02d', hora) %>_<%= dia %>">
			<%= horario_do_dia(hora,dia) %>
			</div>
			</td>
		<% end %>
	</tr>
	<% end %>
</tbody>
</table>

app/views/horarios/excluir.js.erb
<% nome_da_div="dia_#{@horario.horario[0..1]}_#{@horario.dia}" %>
$("#<%= nome_da_div %>").html("<%= j horario_livre(@horario.horario[0..1], @horario.dia) %>");

app/views/horarios/novo.js.erb
<% nome_da_div="dia_#{@horario.horario[0..1]}_#{@horario.dia}" %>
$("#<%= nome_da_div %>").html("<%= j horario_reservado(@horario) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Sistema de reserva de salas" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Reserva de salas', home_index_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
     <% if usuario_signed_in? %>
      <li><%= link_to "Bem vindo(a), #{current_usuario.nome_completo}", "#" %></li>
      <li>
      <%= link_to('Sair', destroy_usuario_session_path, :method => :delete) %>        
      </li>
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
     
      
      
    </ul>
  </section>
</nav>
<div class="row" align="center">
    <%= yield %>
</div>
  </body>
</html>